name: build-and-test-rpn
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        version: [1.20, 1.21]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}
      id: go

    - name: checkout
      uses: actions/checkout@v3

    - name: build
      run: make

    # - name: test
    #   run: make test

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
